### PR TITLE
Feature feedback on post error

### PR DESCRIPTION
**Pull request by quadrophobiac**
This PR addresses https://github.com/theodi/csvlint/issues/200
It halts the validation 'spinner' once a ajax failing response is returned to the jQuery request and displays a warning message

### CODE REVIEW

**Comment by quadrophobiac** [comment]
Do not merge

**Comment by pezholio** [comment]
Right. I've got access to a test Travis instance and I've added some logging to the middleware like so:

```
  def self.mock(path, status, headers = {}, body = "")
    puts "MOCKING PATH = #{path}, STATUS = #{status}"
    @@mocks ||= {}
    @@mocks[path] = [status, headers, body]
    puts @@mocks # Log the mocks
  end

... snip ..

  def call(env)
    puts @@mocks # log the mocks again
    @@mocks.each_pair do |path, response|
      if env["PATH_INFO"] =~ /#{path}/
        puts "MOCKING #{path}"
        return response
      end
    end
    puts "NOPE #{env["PATH_INFO"]}"
    @app.call(env)
  end
```

And here's what I see:

```
    Given I go to the homepage                                                                          # features/step_definitions/web_steps.rb:1
    And I attach the file "csvs/valid.csv" to the "file" field                                          # features/step_definitions/web_steps.rb:27
MOCKING PATH = /package, STATUS = 413
{"/package"=>[413, {}, ""]}
    And the data exceeds the amount the proxy can handle                                                # features/step_definitions/fixture_steps.rb:51
    When I press "Validate"                                                                             # features/step_definitions/web_steps.rb:23
    Then I should see "The request couldn't complete"                                                   # features/step_definitions/web_steps.rb:33
{}
NOPE /package.json
```

So, it seems like the mock gets set up OK, but the middleware state doesn't hang around

**Comment by pezholio** [comment]
Ah ha. Also, adding logging to the reset:

```
  def self.reset
    puts "RESETTING"
    @@mocks = {}
  end
```

I see that the mock is getting reset BEFORE the last step:

```
    When I press "Validate"                                                                             # features/step_definitions/web_steps.rb:23
    Then I should see "The request couldn't complete"                                                   # features/step_definitions/web_steps.rb:33
RESETTING
{}
NOPE /package.json
```

Wut?

**Comment by Floppy** [comment]
@pezholio I was going to bring this up to date with master in an attempt to get it merged again, but there are a couple of conflicts around the javascript uploader, which I thought it might be best to get you to resolve. Can you take a look and bring it up to speed? Ta :)

**Pull request merged**
