### PR TITLE
Delete uploaded CSVs after specified time period

### PR DESCRIPTION
**Pull request by bcouston**
CSVs uploaded from local fluster are now deleted from MongoDB GridFS
after a specified time period (default 24 hours) and Validations model.
See clean_up_uploaded_cvs.rake to set time period.

### CODE REVIEW

**Comment by Floppy** [comment]
@pikesley we'll want to add the rake task added here to a scheduled cron job on the csvlint servers - how much of a pain is that at the moment?

**Comment by Floppy** [comment]
So rather than removing all file storage, which we need to support revalidation with different dialects, the simplest and most predictable way to handle it is instead to clean up all files older than 24 hours; dialect change is considered very unlikely with the same data at that point. This allows us to be sure that the data is purged in a privacy-compatible manner, and that user experience doesn't break in some strange edge case because we're deleting the data too quickly.

@pezholio, can you take a read through this and merge if you're happy? Then we'll work out how to get it running on a regular basis.

Resolves #169

**Comment by pezholio** [comment]
Looks good :+1: 

We probably don't need to add a cron job, as we've got Delayed Job running here, so it would just be a case of running the rake task on deploy and then queueing another run in 24 hours after running the `clean_up` method

**Comment by Floppy** [comment]
ah, interesting. We could do that if a cron is a royal pain. Having jobs requeue themselves always gives me the slight jeebies, but if the alternative is difficult then let's do it.

**Comment by quadrophobiac** [comment]
DO NOT MERGE UNTIL
At present it is unclear where in this code one can create the indexes for validation model. Mongoid doesn't do so automatically, and  ``` rake db:mongoid:create_indexes ``` is advocated as the way of doing this. I have attempted modified the mongoid.yml but that isn't advised for a live environment, so at a loss as to the best way to accomplish this

**Comment by pezholio** [comment]
@quadrophobiac Can you revert this last commit and put it in a different branch? This seems related to #191

**Comment by quadrophobiac** [comment]
@pezholio sorry about that, and the delay, should be ok now

**Comment by pezholio** [comment]
Cool cool, no drama :+1:

**Pull request merged**
