### PR TITLE
Toolbox harmonised readmes

### PR DESCRIPTION
**Pull request by quadrophobiac**
Have brought this repo's readme into line with harmonised template

**FAO Reviewer**
This is one of the repos that has dependencies triggering `therubyracer` and `eventmachine` errors. I have noted these for now under Known Issues

**Feedback Required**
* Is phantomJs a prerequisite for this repo?
* Does running `foreman start` negate need to have a mongodb and redis instance running?
* are there any rake tasks worth noting here?

### CODE REVIEW

**Comment by Floppy** [comment]
* It will need phantomjs for testing
* foreman doesn't have mongodb and redis, so that's still necessary separately

There are a few rake tasks that are run on production:

* `rake csvs:clean_up`
* `rake summary:generate`
* `rake clean_up:dupes`

Off the top of my head I don't know precisely what they do (other than the names), but they're worth covering.

**Comment by quadrophobiac** [comment]
great Ill amend that as appropriate - what should I do about the rubyracer and event machine stuff - currently explained like so
`gem install eventmachine -v '1.0.7' -- --with-cppflags=-I/usr/local/opt/openssl/include`  
`gem install libv8 -v '3.16.14.13' -- --with-system-v8`  
`gem install therubyracer -- --with-v8-dir=/usr/local/opt/v8-315 `  
https://github.com/shakacode/react-webpack-rails-tutorial/issues/266 ~ rubyracer with CSVlint

**Comment by Floppy** [comment]
Hm. I think maybe for that stuff, move it into a troubleshooting section? i.e. if you have problems running bundle, try these things.

**Comment by quadrophobiac** [comment]
KK - I have reordered the layout of the readme and left the instructions in place.
The specific failures here also fail in https://github.com/theodi/open-data-certificate/issues/1452 so I'll keep an eye on that for any amendments required to the readme

**Pull request merged**
