### PR TITLE
Error reporting schema expanded test suite

### PR DESCRIPTION
**Pull request by quadrophobiac**
* additions made to package_controller to catch a JSON error for uploaded JSON files, bit of a cludge tbh, schema_url being used in conditional evaluation when two comparison variables would b e preferable
* changes made to validation.check_schema and validation.validate (initaliase method)
* additional tests added to schemas, a malformed JSON file added for tests (contains JSON syntax error)

### CODE REVIEW

**Comment by quadrophobiac** [comment]
Hey, have made some minor updates to this code, but can't issue another  pull request
details here https://github.com/theodi/csvlint/commit/0d5fb15c2861d2aa6130bff37810822f038f9e0e
schema_url is being set to a boolean if the schema is derived from a file upload. Conditionals where schema_url should be evaluated based on an actual URL being contained in this variable have been updated to include this boolean logic (within Validation model). 
This state of affairs isn't ideal but its the best that can be done for now because it seems schema_url is being used to store and fetch schema urls from the database of all schemas uploaded. Therefore changing this before deciding what is being stored in the database and how it is meant to be accessible isn't possible

**Comment by quadrophobiac** [comment]
Please see this commit for reference (https://github.com/theodi/csvlint/commit/2aeaead7a1295eddc1609161cd6ee4e5a21b87c8)
The bulk of the function package_controller.read_data is currently only utilised by the test spec package_controller_spec
lines 136 - 162 will trigger the read_data *data.each do |data|* block, and I believe that is due to the way that it makes the csv and schema files available>
I have written corresponding schemas in schemas.feature but they do not trigger the behaviour. This is because the Object passed to the read_data in the scenarios is of ActionDispatch::Http::UploadedFile type, which doesn't have an each method.
The successfully passing spec test 'package_controller_spec' (referenced above) passes an array, which does have an each method

**Comment by Floppy** [comment]
Ooh, interesting. I guess that means that the spec test is insufficient, because the real app would look more like the feature, right? Should we adjust the spec to pass in the right object, do you think?

**Comment by quadrophobiac** [comment]
Yes I think so, just need to understand a bit better what behaviour is stipulated in the schemas respective to what the specs are emulating

**Comment by bcouston** [comment]
@Floppy  and @pezholio can you give us some insight as to what the badge method was supposed to do? Has it been deprecated?

**Comment by pezholio** [comment]
@bcouston I don't actually know - I seem to have plonked a blank method in there for now good reason :confounded:

**Comment by quadrophobiac** [comment]
This issue is now dependent on this branch of csvlint.rb https://github.com/theodi/csvlint.rb/tree/error-reporting-schema_expanded-test-suite

**Comment by quadrophobiac** [comment]
In terms of https://github.com/theodi/csvlint/issues/186 reported the current code will report better JSON errors

* invalid regex
* invalid values for a constraint specification, e.g. a number or string where true/false is expected
* unknown constraint

are not currently implemented - would entail a more thorough rewrite of csvlint.rb and therefore issue is better moved to that repo.

DO NOT MERGE UNTIL -  
The current branch needs to work with this branch of csvlint.rb  https://github.com/theodi/csvlint.rb/tree/error-reporting-schema_expanded-test-suite

**Comment by pezholio** [comment]
I've updated the gem now, but we still have fail :cry:

**Comment by bcouston** [comment]
@pezholio and @quadrophobiac this sounds like it still needs some work, definitely not ready for merge I'm assuming?

**Comment by bcouston** [comment]
Updated to master, there were 4 failing features and now there are 2.

Before:
screen shot 2015-08-20 at 11 28 26

After:
screen shot 2015-08-20 at 11 28 31

**Pull request merged**
